### ISSUE TITLE
repeated crashing on initial scan

### ISSUE THREAD

**Issue by aeleeds** [navidrome/navidrome#1599]
I installed Navidrome today on my pi 2B+, raspian bullseye, v0.47.5. It is repeatedly crashing on initial scan of my music library. Here's an example of the log output:

```
Feb 04 19:55:25 raspberrypi navidrome[17982]: time="2022-02-04T19:55:25Z" level=info msg="Finished processing changed folder" deleted=0 dir="/mnt/consolidated/Brian Eno & Joh>
Feb 04 19:55:26 raspberrypi navidrome[17982]: time="2022-02-04T19:55:26Z" level=info msg="Finished processing changed folder" deleted=0 dir="/mnt/consolidated/Brian Eno & Lar>
Feb 04 19:55:26 raspberrypi navidrome[17982]: time="2022-02-04T19:55:26Z" level=info msg="Finished processing changed folder" deleted=0 dir="/mnt/consolidated/Brian Eno & Rob>
Feb 04 19:55:27 raspberrypi navidrome[17982]: time="2022-02-04T19:55:27Z" level=info msg="Finished processing changed folder" deleted=0 dir="/mnt/consolidated/Brian Eno & Rob>
Feb 04 19:55:28 raspberrypi navidrome[17982]: time="2022-02-04T19:55:28Z" level=info msg="Finished processing changed folder" deleted=0 dir="/mnt/consolidated/Brian Eno, Moeb>
Feb 04 19:55:29 raspberrypi navidrome[17982]: fatal error: unexpected signal during runtime execution
Feb 04 19:55:29 raspberrypi navidrome[17982]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x43 pc=0x768c1c]
Feb 04 19:55:29 raspberrypi navidrome[17982]: runtime stack:
Feb 04 19:55:29 raspberrypi navidrome[17982]: runtime.throw({0xa1ee96, 0x2a})
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /usr/local/go/src/runtime/panic.go:1198 +0x5c
Feb 04 19:55:29 raspberrypi navidrome[17982]: runtime.sigpanic()
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /usr/local/go/src/runtime/signal_unix.go:719 +0x218
Feb 04 19:55:29 raspberrypi navidrome[17982]: goroutine 42 [syscall]:
Feb 04 19:55:29 raspberrypi navidrome[17982]: runtime.cgocall(0x75f234, 0x2fda010)
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /usr/local/go/src/runtime/cgocall.go:156 +0x5c fp=0x2fd9ff8 sp=0x2fd9fe0 pc=0x1dfdc
Feb 04 19:55:29 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/scanner/metadata/taglib._Cfunc_taglib_read(0x600ffce0, 0x2f61)
Feb 04 19:55:29 raspberrypi navidrome[17982]:         _cgo_gotypes.go:82 +0x34 fp=0x2fda00c sp=0x2fd9ff8 pc=0x66539c
Feb 04 19:55:29 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/scanner/metadata/taglib.Read({0x3242070, 0x69})
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /github/workspace/scanner/metadata/taglib/taglib_wrapper.go:39 +0xe0 fp=0x2fda0d0 sp=0x2fda00c pc=0x66554c
Feb 04 19:55:29 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/scanner/metadata/taglib.(*Parser).extractMetadata(0x213de20, {0x3242070, 0x69})
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /github/workspace/scanner/metadata/taglib/taglib.go:22 +0x28 fp=0x2fda25c sp=0x2fda0d0 pc=0x664bb4
Feb 04 19:55:29 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/scanner/metadata/taglib.(*Parser).Parse(0x213de20, {0x2ea6000, 0xe, 0x10})
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /github/workspace/scanner/metadata/taglib/taglib.go:16 +0x6c fp=0x2fda288 sp=0x2fda25c pc=0x664b00
Feb 04 19:55:29 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/scanner/metadata.Extract({0x2ea6000, 0xe, 0x10})
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /github/workspace/scanner/metadata/metadata.go:38 +0x158 fp=0x2fda360 sp=0x2fda288 pc=0x666254
Feb 04 19:55:29 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/scanner.(*TagScanner).loadTracks(0x2f3e960, {0x2ea6000, 0xe, 0x10})
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /github/workspace/scanner/tag_scanner.go:374 +0x30 fp=0x2fda6f8 sp=0x2fda360 pc=0x670348
Feb 04 19:55:29 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/scanner.(*TagScanner).addOrUpdateTracksInDB(0x2f3e960, {0x1d1ba60, 0x2c265d0}, {0x3231020, 0x2e},>
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /github/workspace/scanner/tag_scanner.go:349 +0x26c fp=0x2fdac8c sp=0x2fda6f8 pc=0x66ff24
Feb 04 19:55:29 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/scanner.(*TagScanner).processChangedDir(0x2f3e960, {0x1d1ba60, 0x2c265d0}, {0x3231020, 0x2e}, 0x1)
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /github/workspace/scanner/tag_scanner.go:301 +0x8e0 fp=0x2fdb794 sp=0x2fdac8c pc=0x66f69c
Feb 04 19:55:29 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/scanner.(*TagScanner).Scan(0x2f3e960, {0x1d1ba20, 0x2cac000}, {0x0, 0x0, 0x0}, 0x2eae000)
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /github/workspace/scanner/tag_scanner.go:101 +0x5a4 fp=0x2fdbd90 sp=0x2fdb794 pc=0x66d6b4
Feb 04 19:55:29 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/scanner.(*scanner).rescan(0x2f3e900, {0x1d1ba20, 0x2cac000}, {0x2f3a0c0, 0x12}, 0x0)
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /github/workspace/scanner/scanner.go:93 +0x2b0 fp=0x2fdbeec sp=0x2fdbd90 pc=0x66b83c
Feb 04 19:55:29 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/scanner.(*scanner).RescanAll(0x2f3e900, {0x1d1ba20, 0x2cac000}, 0x0)
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /github/workspace/scanner/scanner.go:152 +0x1a0 fp=0x2fdbf6c sp=0x2fdbeec pc=0x66c0f8
Feb 04 19:55:29 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/cmd.schedulePeriodicScan({0x9fb0b6, 0x9})
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /github/workspace/cmd/root.go:141 +0x208 fp=0x2fdbfe4 sp=0x2fdbf6c pc=0x6ac5d4
Feb 04 19:55:29 raspberrypi navidrome[17982]: runtime.goexit()
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /usr/local/go/src/runtime/asm_arm.s:838 +0x4 fp=0x2fdbfe4 sp=0x2fdbfe4 pc=0x8aa34
Feb 04 19:55:29 raspberrypi navidrome[17982]: created by github.com/navidrome/navidrome/cmd.runNavidrome
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /github/workspace/cmd/root.go:65 +0x230
Feb 04 19:55:29 raspberrypi navidrome[17982]: goroutine 1 [chan receive, 18 minutes]:
Feb 04 19:55:29 raspberrypi navidrome[17982]: github.com/oklog/run.(*Group).Run(0x2c4ee54)
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:43 +0xd8
Feb 04 19:55:29 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/cmd.runNavidrome()
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /github/workspace/cmd/root.go:70 +0x280
Feb 04 19:55:29 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/cmd.glob..func2(0x20e5580, {0x2f20080, 0x0, 0x2})
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /github/workspace/cmd/root.go:33 +0x14
Feb 04 19:55:29 raspberrypi navidrome[17982]: github.com/spf13/cobra.(*Command).execute(0x20e5580, {0x2cba008, 0x2, 0x2})
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x644
Feb 04 19:55:29 raspberrypi navidrome[17982]: github.com/spf13/cobra.(*Command).ExecuteC(0x20e5580)
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x414
Feb 04 19:55:29 raspberrypi navidrome[17982]: github.com/spf13/cobra.(*Command).Execute(...)
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
Feb 04 19:55:29 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/cmd.Execute()
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /github/workspace/cmd/root.go:41 +0x58
Feb 04 19:55:29 raspberrypi navidrome[17982]: main.main()
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /github/workspace/main.go:15 +0x12c
Feb 04 19:55:29 raspberrypi navidrome[17982]: goroutine 35 [select, 18 minutes]:
Feb 04 19:55:29 raspberrypi navidrome[17982]: database/sql.(*DB).connectionOpener(0x2f154d0, {0x1d1ba00, 0x2f3e360})
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /usr/local/go/src/database/sql/sql.go:1196 +0x9c
Feb 04 19:55:29 raspberrypi navidrome[17982]: created by database/sql.OpenDB
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /usr/local/go/src/database/sql/sql.go:794 +0x134
Feb 04 19:55:29 raspberrypi navidrome[17982]: goroutine 34 [syscall, 18 minutes]:
Feb 04 19:55:29 raspberrypi navidrome[17982]: os/signal.signal_recv()
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /usr/local/go/src/runtime/sigqueue.go:169 +0xf0
Feb 04 19:55:29 raspberrypi navidrome[17982]: os/signal.loop()
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /usr/local/go/src/os/signal/signal_unix.go:24 +0x14
Feb 04 19:55:29 raspberrypi navidrome[17982]: created by os/signal.Notify.func1.1
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /usr/local/go/src/os/signal/signal.go:151 +0x30
Feb 04 19:55:29 raspberrypi navidrome[17982]: goroutine 22 [chan receive, 18 minutes]:
Feb 04 19:55:29 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/utils/singleton.init.0.func1()
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /github/workspace/utils/singleton/singleton.go:36 +0x54
Feb 04 19:55:29 raspberrypi navidrome[17982]: created by github.com/navidrome/navidrome/utils/singleton.init.0
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /github/workspace/utils/singleton/singleton.go:34 +0x24
Feb 04 19:55:29 raspberrypi navidrome[17982]: goroutine 37 [chan receive, 18 minutes]:
Feb 04 19:55:29 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/utils/pool.(*worker).Start.func1(0x2f11878)
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /github/workspace/utils/pool/pool.go:86 +0x7c
Feb 04 19:55:29 raspberrypi navidrome[17982]: created by github.com/navidrome/navidrome/utils/pool.(*worker).Start
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /github/workspace/utils/pool/pool.go:85 +0x2c
Feb 04 19:55:29 raspberrypi navidrome[17982]: goroutine 38 [chan receive, 18 minutes]:
Feb 04 19:55:29 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/utils/pool.(*worker).Start.func1(0x2f11888)
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /github/workspace/utils/pool/pool.go:86 +0x7c
Feb 04 19:55:29 raspberrypi navidrome[17982]: created by github.com/navidrome/navidrome/utils/pool.(*worker).Start
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /github/workspace/utils/pool/pool.go:85 +0x2c
Feb 04 19:55:29 raspberrypi navidrome[17982]: goroutine 39 [chan receive, 18 minutes]:
Feb 04 19:55:29 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/utils/pool.(*worker).Start.func1(0x2f11890)
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /github/workspace/utils/pool/pool.go:86 +0x7c
Feb 04 19:55:29 raspberrypi navidrome[17982]: created by github.com/navidrome/navidrome/utils/pool.(*worker).Start
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /github/workspace/utils/pool/pool.go:85 +0x2c
Feb 04 19:55:29 raspberrypi navidrome[17982]: goroutine 40 [select]:
Feb 04 19:55:29 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/utils/pool.NewPool.func1(0x2f3e870)
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /github/workspace/utils/pool/pool.go:45 +0xb4
Feb 04 19:55:29 raspberrypi navidrome[17982]: created by github.com/navidrome/navidrome/utils/pool.NewPool
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /github/workspace/utils/pool/pool.go:41 +0x228
Feb 04 19:55:29 raspberrypi navidrome[17982]: goroutine 41 [select]:
Feb 04 19:55:29 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/server/events.(*broker).listen(0x2f20b10)
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /github/workspace/server/events/sse.go:208 +0x134
Feb 04 19:55:29 raspberrypi navidrome[17982]: created by github.com/navidrome/navidrome/server/events.GetBroker.func1
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /github/workspace/server/events/sse.go:77 +0xe8
Feb 04 19:55:29 raspberrypi navidrome[17982]: goroutine 43 [IO wait, 18 minutes]:
Feb 04 19:55:29 raspberrypi navidrome[17982]: internal/poll.runtime_pollWait(0x653d5f80, 0x72)
Feb 04 19:55:29 raspberrypi navidrome[17982]:         /usr/local/go/src/runtime/netpoll.go:229 +0xac
Feb 04 19:55:29 raspberrypi systemd[1]: navidrome.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 04 19:55:30 raspberrypi navidrome[17982]: internal/poll.(*pollDesc).wait(0x3031964, 0x72, 0x0)
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x30
Feb 04 19:55:30 raspberrypi navidrome[17982]: internal/poll.(*pollDesc).waitRead(...)
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /usr/local/go/src/internal/poll/fd_poll_runtime.go:89
Feb 04 19:55:30 raspberrypi navidrome[17982]: internal/poll.(*FD).Accept(0x3031950)
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /usr/local/go/src/internal/poll/fd_unix.go:402 +0x234
Feb 04 19:55:30 raspberrypi navidrome[17982]: net.(*netFD).accept(0x3031950)
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /usr/local/go/src/net/fd_unix.go:173 +0x20
Feb 04 19:55:30 raspberrypi navidrome[17982]: net.(*TCPListener).accept(0x2c0e5b0)
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /usr/local/go/src/net/tcpsock_posix.go:140 +0x20
Feb 04 19:55:30 raspberrypi navidrome[17982]: net.(*TCPListener).Accept(0x2c0e5b0)
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /usr/local/go/src/net/tcpsock.go:262 +0x30
Feb 04 19:55:30 raspberrypi navidrome[17982]: net/http.(*Server).Serve(0x2c70870, {0x1d1b664, 0x2c0e5b0})
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /usr/local/go/src/net/http/server.go:3001 +0x320
Feb 04 19:55:30 raspberrypi navidrome[17982]: net/http.(*Server).ListenAndServe(0x2c70870)
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /usr/local/go/src/net/http/server.go:2930 +0xa4
Feb 04 19:55:30 raspberrypi navidrome[17982]: net/http.ListenAndServe(...)
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /usr/local/go/src/net/http/server.go:3184
Feb 04 19:55:30 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/server.(*Server).Run(0x3012018, {0x2c2a620, 0xc})
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /github/workspace/server/server.go:48 +0x1a8
Feb 04 19:55:30 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/cmd.startServer.func1()
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /github/workspace/cmd/root.go:86 +0x1f4
Feb 04 19:55:30 raspberrypi navidrome[17982]: github.com/oklog/run.(*Group).Run.func1(0x2f47b40, {0x1c50290, 0x1c50294})
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38 +0x1c
Feb 04 19:55:30 raspberrypi navidrome[17982]: created by github.com/oklog/run.(*Group).Run
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:37 +0x98
Feb 04 19:55:30 raspberrypi navidrome[17982]: goroutine 44 [select, 18 minutes]:
Feb 04 19:55:30 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/cmd.startSignaler.func1()
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /github/workspace/cmd/root.go:104 +0xc4
Feb 04 19:55:30 raspberrypi navidrome[17982]: github.com/oklog/run.(*Group).Run.func1(0x2f47b40, {0x2f2a558, 0x2f11b20})
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38 +0x1c
Feb 04 19:55:30 raspberrypi navidrome[17982]: created by github.com/oklog/run.(*Group).Run
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:37 +0x98
Feb 04 19:55:30 raspberrypi navidrome[17982]: goroutine 45 [chan receive, 18 minutes]:
Feb 04 19:55:30 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/scheduler.(*scheduler).Run(0x2f11b68, {0x1d1ba00, 0x2f3e9f0})
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /github/workspace/scheduler/scheduler.go:31 +0x48
Feb 04 19:55:30 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/cmd.startScheduler.func1()
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /github/workspace/cmd/root.go:153 +0x34
Feb 04 19:55:30 raspberrypi navidrome[17982]: github.com/oklog/run.(*Group).Run.func1(0x2f47b40, {0x2f2a570, 0x2f11b80})
Feb 04 19:55:29 raspberrypi systemd[1]: navidrome.service: Failed with result 'exit-code'.
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38 +0x1c
Feb 04 19:55:30 raspberrypi navidrome[17982]: created by github.com/oklog/run.(*Group).Run
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:37 +0x98
Feb 04 19:55:30 raspberrypi navidrome[17982]: goroutine 46 [select]:
Feb 04 19:55:30 raspberrypi navidrome[17982]: github.com/robfig/cron/v3.(*Cron).run(0x2f52ae0)
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:263 +0xaa4
Feb 04 19:55:30 raspberrypi navidrome[17982]: created by github.com/robfig/cron/v3.(*Cron).Start
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:222 +0x9c
Feb 04 19:55:30 raspberrypi navidrome[17982]: goroutine 52 [select, 18 minutes]:
Feb 04 19:55:30 raspberrypi navidrome[17982]: github.com/ReneKroon/ttlcache/v2.(*Cache).startExpirationProcessing(0x3016b40)
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /go/pkg/mod/github.com/!rene!kroon/ttlcache/v2@v2.11.0/cache.go:147 +0x350
Feb 04 19:55:30 raspberrypi navidrome[17982]: created by github.com/ReneKroon/ttlcache/v2.NewCache
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /go/pkg/mod/github.com/!rene!kroon/ttlcache/v2@v2.11.0/cache.go:577 +0x1d4
Feb 04 19:55:30 raspberrypi navidrome[17982]: goroutine 53 [select, 18 minutes]:
Feb 04 19:55:30 raspberrypi navidrome[17982]: github.com/ReneKroon/ttlcache/v2.(*Cache).startExpirationProcessing(0x3016cf0)
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /go/pkg/mod/github.com/!rene!kroon/ttlcache/v2@v2.11.0/cache.go:147 +0x350
Feb 04 19:55:30 raspberrypi navidrome[17982]: created by github.com/ReneKroon/ttlcache/v2.NewCache
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /go/pkg/mod/github.com/!rene!kroon/ttlcache/v2@v2.11.0/cache.go:577 +0x1d4
Feb 04 19:55:30 raspberrypi navidrome[17982]: goroutine 54 [select, 18 minutes]:
Feb 04 19:55:30 raspberrypi navidrome[17982]: github.com/ReneKroon/ttlcache/v2.(*Cache).startExpirationProcessing(0x3016d80)
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /go/pkg/mod/github.com/!rene!kroon/ttlcache/v2@v2.11.0/cache.go:147 +0x350
Feb 04 19:55:30 raspberrypi navidrome[17982]: created by github.com/ReneKroon/ttlcache/v2.NewCache
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /go/pkg/mod/github.com/!rene!kroon/ttlcache/v2@v2.11.0/cache.go:577 +0x1d4
Feb 04 19:55:30 raspberrypi navidrome[17982]: goroutine 55 [chan receive, 18 minutes]:
Feb 04 19:55:30 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/core/scrobbler.(*bufferedScrobbler).run(0x31300e0)
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /github/workspace/core/scrobbler/buffered_scrobbler.go:59 +0x38
Feb 04 19:55:30 raspberrypi navidrome[17982]: created by github.com/navidrome/navidrome/core/scrobbler.newBufferedScrobbler
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /github/workspace/core/scrobbler/buffered_scrobbler.go:14 +0x10c
Feb 04 19:55:30 raspberrypi navidrome[17982]: goroutine 56 [select, 18 minutes]:
Feb 04 19:55:30 raspberrypi navidrome[17982]: github.com/ReneKroon/ttlcache/v2.(*Cache).startExpirationProcessing(0x3016ea0)
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /go/pkg/mod/github.com/!rene!kroon/ttlcache/v2@v2.11.0/cache.go:147 +0x350
Feb 04 19:55:30 raspberrypi navidrome[17982]: created by github.com/ReneKroon/ttlcache/v2.NewCache
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /go/pkg/mod/github.com/!rene!kroon/ttlcache/v2@v2.11.0/cache.go:577 +0x1d4
Feb 04 19:55:29 raspberrypi systemd[1]: navidrome.service: Consumed 9min 45.677s CPU time.
Feb 04 19:55:30 raspberrypi navidrome[17982]: goroutine 57 [chan receive, 18 minutes]:
Feb 04 19:55:30 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/core/scrobbler.(*bufferedScrobbler).run(0x3130140)
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /github/workspace/core/scrobbler/buffered_scrobbler.go:59 +0x38
Feb 04 19:55:30 raspberrypi navidrome[17982]: created by github.com/navidrome/navidrome/core/scrobbler.newBufferedScrobbler
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /github/workspace/core/scrobbler/buffered_scrobbler.go:14 +0x10c
Feb 04 19:55:30 raspberrypi navidrome[17982]: goroutine 24 [select]:
Feb 04 19:55:30 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/scanner.(*scanner).startProgressTracker.func1(0x2f3e900, {0x1d1ba00, 0x2f3e3c0}, {0x2f3a0c0, 0x12>
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /github/workspace/scanner/scanner.go:122 +0x134
Feb 04 19:55:30 raspberrypi navidrome[17982]: created by github.com/navidrome/navidrome/scanner.(*scanner).startProgressTracker
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /github/workspace/scanner/scanner.go:112 +0x9c
Feb 04 19:55:30 raspberrypi navidrome[17982]: goroutine 25 [select, 18 minutes]:
Feb 04 19:55:30 raspberrypi navidrome[17982]: github.com/ReneKroon/ttlcache/v2.(*Cache).startExpirationProcessing(0x2cddc20)
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /go/pkg/mod/github.com/!rene!kroon/ttlcache/v2@v2.11.0/cache.go:147 +0x350
Feb 04 19:55:30 raspberrypi navidrome[17982]: created by github.com/ReneKroon/ttlcache/v2.NewCache
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /go/pkg/mod/github.com/!rene!kroon/ttlcache/v2@v2.11.0/cache.go:577 +0x1d4
Feb 04 19:55:30 raspberrypi navidrome[17982]: goroutine 26 [chan send]:
Feb 04 19:55:30 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/scanner.walkFolder({0x1d1ba60, 0x2c265d0}, {0x2f3a0c0, 0x12}, {0x2f559b0, 0x2a}, 0x2c29880)
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /github/workspace/scanner/walk_dir_tree.go:54 +0x25c
Feb 04 19:55:30 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/scanner.walkFolder({0x1d1ba60, 0x2c265d0}, {0x2f3a0c0, 0x12}, {0x3119b60, 0x1b}, 0x2c29880)
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /github/workspace/scanner/walk_dir_tree.go:44 +0xd8
Feb 04 19:55:30 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/scanner.walkFolder({0x1d1ba60, 0x2c265d0}, {0x2f3a0c0, 0x12}, {0x2f3a0c0, 0x12}, 0x2c29880)
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /github/workspace/scanner/walk_dir_tree.go:44 +0xd8
Feb 04 19:55:30 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/scanner.walkDirTree({0x1d1ba60, 0x2c265d0}, {0x2f3a0c0, 0x12}, 0x2c29880)
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /github/workspace/scanner/walk_dir_tree.go:30 +0x44
Feb 04 19:55:30 raspberrypi navidrome[17982]: github.com/navidrome/navidrome/scanner.(*TagScanner).getRootFolderWalker.func1({0x1d1ba60, 0x2c265d0}, 0x2f3e960, 0x2c29880, 0x2>
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /github/workspace/scanner/tag_scanner.go:164 +0x40
Feb 04 19:55:30 raspberrypi navidrome[17982]: created by github.com/navidrome/navidrome/scanner.(*TagScanner).getRootFolderWalker
Feb 04 19:55:29 raspberrypi systemd[1]: navidrome.service: Scheduled restart job, restart counter is at 12.
Feb 04 19:55:30 raspberrypi navidrome[17982]:         /github/workspace/scanner/tag_scanner.go:163 +0x130
Feb 04 19:55:29 raspberrypi systemd[1]: Stopped Navidrome Music Server and Streamer compatible 
```

**Comment by niaiai** [comment]
try configure `Scanner.Extractor = 'ffmpeg'`

**Comment by raminou** [comment]
I had the same issue with the same rpi model.

Changing the CI_RELEASER_VERSION from 1.17.2-1 to 1.18.1-1 in the Makefile fixed the issue.

**Comment by ssj4maiko** [comment]
Similar to niaiai's solution, for those who are running straight from Docker (or a similar package like Yacht), you can add the following variable to the .env (Environment Variables)
`ND_SCANNER_EXTRACTOR=ffmpeg`
