### ISSUE TITLE
Crash during scanning

### ISSUE THREAD

**Issue by ahoy** [navidrome/navidrome#1796]
I'm regularly getting this crash after a while (47ksec in this case). 

```
| \ | |           (_)   | |
|  \| | __ ___   ___  __| |_ __ ___  _ __ ___   ___
| . ` |/ _` \ \ / / |/ _` | '__/ _ \| '_ ` _ \ / _ \
| |\  | (_| |\ V /| | (_| | | | (_) | | | | | |  __/
\_| \_/\__,_| \_/ |_|\__,_|_|  \___/|_| |_| |_|\___|
                          Version: 0.47.5 (86fe1e3b)

Loaded configuration from '/usr/local/etc/navidrome.toml': &conf.configOptions{
    ConfigFile:                 "/usr/local/etc/navidrome.toml",
    Address:                    "0.0.0.0",
    Port:                       4533,
    MusicFolder:                "/media/music",
    DataFolder:                 "/var/db/navidrome",
    DbPath:                     "/var/db/navidrome/navidrome.db?cache=shared&_busy_timeout=15000&_journal_mode=WAL&_foreign_keys=on",
    LogLevel:                   "DEBUG",
    ScanInterval:               -1,
    ScanSchedule:               "@every 1m",
    SessionTimeout:             86400000000000,
    BaseURL:                    "",
    UILoginBackgroundURL:       "https://source.unsplash.com/collection/20072696/1600x900",
    EnableTranscodingConfig:    true,
    EnableDownloads:            true,
    EnableExternalServices:     true,
    TranscodingCacheSize:       "500MiB",
    ImageCacheSize:             "100MB",
    AutoImportPlaylists:        true,
    PlaylistsPath:              ".:**/**",
    SearchFullString:           false,
    RecentlyAddedByModTime:     false,
    IgnoredArticles:            "The El La Los Las Le Les Os As O A",
    IndexGroups:                "A B C D E F G H I J K L M N O P Q R S T U V W X-Z(XYZ) [Unknown]([)",
    ProbeCommand:               "ffmpeg %s -f ffmetadata",
    CoverArtPriority:           "embedded, cover.*, folder.*, front.*",
    CoverJpegQuality:           75,
    UIWelcomeMessage:           "",
    EnableGravatar:             false,
    EnableFavourites:           true,
    EnableStarRating:           true,
    EnableUserEditing:          true,
    DefaultTheme:               "Dark",
    EnableCoverAnimation:       true,
    GATrackingID:               "",
    EnableLogRedacting:         true,
    AuthRequestLimit:           5,
    AuthWindowLength:           20000000000,
    PasswordEncryptionKey:      "[REDACTED]",
    ReverseProxyUserHeader:     "Remote-User",
    ReverseProxyWhitelist:      "",
    Scanner:                    conf.scannerOptions{Extractor:"taglib", GenreSeparators:";/,"},
    Agents:                     "lastfm,spotify",
    LastFM:                     conf.lastfmOptions{Enabled:true, ApiKey:"[REDACTED]", Secret:"[REDACTED]", Language:"en"},
    Spotify:                    conf.spotifyOptions{},
    ListenBrainz:               conf.listenBrainzOptions{Enabled:true},
    DevLogSourceLine:           false,
    DevLogLevels:               {},
    DevAutoCreateAdminPassword: "",
    DevAutoLoginUsername:       "",
    DevPreCacheAlbumArtwork:    false,
    DevFastAccessCoverArt:      false,
    DevActivityPanel:           true,
    DevEnableShare:             false,
    DevSidebarPlaylists:        true,
    DevEnableBufferedScrobble:  true,
    DevShowArtistPage:          true,
}
DEBU[0001] Opening DataBase                              dbPath="/var/db/navidrome/navidrome.db?cache=shared&_busy_timeout=15000&_journal_mode=WAL&_foreign_keys=on" driver=sqlite3
INFO[0001] goose: no migrations to run. current version: 20211105162746 
INFO[0001] Creating Image cache                          maxSize="100 MB" path=/var/db/navidrome/cache/images
INFO[0001] Configuring Media Folder                      name="Music Library" path=/media/music
INFO[0001] Starting scheduler                           
DEBU[0001] Scheduler: start                             
INFO[0001] Scheduling periodic scan                      schedule="@every 1m"
DEBU[0001] Scheduler: added                              entry=1 next="2022-07-03 03:49:52 -0500 CDT" now="2022-07-03 03:48:52.567773463 -0500 CDT"
INFO[0001] Setting Session Timeout                       value=24h
INFO[0001] Login rate limit set                          requestLimit=5 windowLength=20s
INFO[0001] Found ffmpeg                                  path=/usr/local/bin/ffmpeg
DEBU[0001] Last.FM integration is ENABLED               
DEBU[0001] ListenBrainz integration is ENABLED          
INFO[0001] Spotify integration is not enabled: missing ID/Secret 
INFO[0001] Mounting Native API routes                    path=/api
ERRO[0001] Agent not available. Check configuration      name=spotify
INFO[0001] Creating Transcoding cache                    maxSize="524 MB" path=/var/db/navidrome/cache/transcoding
INFO[0001] Mounting Subsonic API routes                  path=/rest
INFO[0001] Mounting LastFM Auth routes                   path=/api/lastfm
INFO[0001] Mounting ListenBrainz Auth routes             path=/api/listenbrainz
INFO[0001] Mounting WebUI routes                         path=/app
INFO[0001] Navidrome server is ready!                    address="0.0.0.0:4533" startupTime=842.8ms
```
...
```
DEBU[47281] Directory tree loaded from DB                 elapsed=42.1ms total=484
DEBU[47281] Finished reading directories from filesystem  elapsed=256.7ms
DEBU[47281] Finished deleted folders check                elapsed="98.224µs" total=0
DEBU[47281] No changes found in Music Folder              elapsed=307.6ms folder=/media/music
DEBU[47341] Scheduler: wake                               now="2022-07-03 16:57:52.004332982 -0500 CDT"
DEBU[47341] Scheduler: run                                entry=1 next="2022-07-03 16:58:52 -0500 CDT" now="2022-07-03 16:57:52.004332982 -0500 CDT"
DEBU[47341] Scanning folder                               folder=/media/music lastModifiedSince="2022-07-03 16:56:52.004 -0500 CDT"
DEBU[47341] Directory tree loaded from DB                 elapsed=48.8ms total=484
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xa985e5]

goroutine 390928 [running]:
github.com/navidrome/navidrome/scanner.fullReadDir.func1(0xc00034e390, 0x0)
	/github/workspace/scanner/walk_dir_tree.go:127 +0x45
sort.medianOfThree_func({0xc000469778, 0xc00034e390}, 0xc001de1c20, 0x203000, 0x10)
	/usr/local/go/src/sort/zfuncversion.go:56 +0x76
sort.doPivot_func({0xc000469778, 0xc00034e390}, 0x0, 0xd)
	/usr/local/go/src/sort/zfuncversion.go:80 +0x115
sort.quickSort_func({0xc000469778, 0xc00034e390}, 0xc001de1c20, 0x0, 0x0)
	/usr/local/go/src/sort/zfuncversion.go:143 +0x85
sort.Slice({0xda3c60, 0xc001de1c20}, 0xd)
	/usr/local/go/src/sort/slice.go:20 +0x9f
github.com/navidrome/navidrome/scanner.fullReadDir({0x21d7980, 0xc00078bfb0}, {0x21d7de0, 0xc00028df50})
	/github/workspace/scanner/walk_dir_tree.go:127 +0x385
github.com/navidrome/navidrome/scanner.loadDir({0x21d7980, 0xc00078bfb0}, {0xc001dc4100, 0x20})
	/github/workspace/scanner/walk_dir_tree.go:77 +0x2f9
github.com/navidrome/navidrome/scanner.walkFolder({0x21d7980, 0xc00078bfb0}, {0xc000038200, 0xc}, {0xc001dc4100, 0x20}, 0x5b)
	/github/workspace/scanner/walk_dir_tree.go:39 +0x71
github.com/navidrome/navidrome/scanner.walkFolder({0x21d7980, 0xc00078bfb0}, {0xc000038200, 0xc}, {0xc0011e83a0, 0x10}, 0x2000)
	/github/workspace/scanner/walk_dir_tree.go:44 +0x2c8
github.com/navidrome/navidrome/scanner.walkFolder({0x21d7980, 0xc00078bfb0}, {0xc000038200, 0xc}, {0xc000038200, 0xc}, 0xc00022e2a0)
	/github/workspace/scanner/walk_dir_tree.go:44 +0x2c8
github.com/navidrome/navidrome/scanner.walkDirTree({0x21d7980, 0xc00078bfb0}, {0xc000038200, 0x889880338}, 0xc0004bc680)
	/github/workspace/scanner/walk_dir_tree.go:30 +0x56
github.com/navidrome/navidrome/scanner.(*TagScanner).getRootFolderWalker.func1()
	/github/workspace/scanner/tag_scanner.go:164 +0x66
created by github.com/navidrome/navidrome/scanner.(*TagScanner).getRootFolderWalker
	/github/workspace/scanner/tag_scanner.go:163 +0x211
```

### Platform information

 - Navidrome version: Version: 0.47.5 (86fe1e3b) (binary)
 - Browser and version: Client: Firefox 101.0.1
 - Operating System: Server: Freebsd 12.3-RELEASE-p5

### Additional information

 - Logs? I turned logging as high as I know how. Let me know if there is more I can do here.
 - Client used? Browser

**Comment by deluan** [comment]
Are you still having this erro? Seems to be a permission issue... Let me know and I can prepare a build with lots of trace info help figure out what is going on

**Comment by ahoy** [comment]
Still happening, although it is somewhat random, and I can go for days without a crash. I'd be happy to run a trace build.

**Comment by ahoy** [comment]
@deluan would you be able to create a debug build?

**Comment by deluan** [comment]
Sorry for the long delay. I see you are using `LOG_LEVEL="debug"`, try setting it to `"trace"`, that you give (tons) more info. You will have to be careful if you are storing the logs, as they will grow exponentially during scans.

**Comment by ahoy** [comment]
The trace log file is huge, as you warned. There are many of the same lines above this point as it scans my media. Not practical to attach the whole log, so if there is anything I can look for, please let me know! 

```time="2022-09-11T09:38:19-05:00" level=trace msg="Broker received new event" event="{0 scanStatus {\"scanning\":true,\"count\":2402,\"folderCount\":238} 0xc005036200}"
time="2022-09-11T09:38:19-05:00" level=trace msg="Got new published event" event="{1696797 scanStatus {\"scanning\":true,\"count\":2402,\"folderCount\":238} 0xc005036200}"
time="2022-09-11T09:38:19-05:00" level=trace msg="Found directory" audioCount=10 dir="/media/M/Final" hasImages=true hasPlaylist=false
time="2022-09-11T09:38:19-05:00" level=trace msg="Broker received new event" event="{0 scanStatus {\"scanning\":true,\"count\":2412,\"folderCount\":239} 0xc005036200}"
time="2022-09-11T09:38:19-05:00" level=trace msg="Got new published event" event="{1696798 scanStatus {\"scanning\":true,\"count\":2412,\"folderCount\":239} 0xc005036200}"
time="2022-09-11T09:38:19-05:00" level=trace msg="Found directory" audioCount=4 dir="/media/M/core" hasImages=true hasPlaylist=false
time="2022-09-11T09:38:19-05:00" level=trace msg="Broker received new event" event="{0 scanStatus {\"scanning\":true,\"count\":2416,\"folderCount\":240} 0xc005036200}"
time="2022-09-11T09:38:19-05:00" level=trace msg="Got new published event" event="{1696799 scanStatus {\"scanning\":true,\"count\":2416,\"folderCount\":240} 0xc005036200}"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xa985e5]

goroutine 3179890 [running]:
github.com/navidrome/navidrome/scanner.fullReadDir.func1(0xc0066698f0, 0x0)
        /github/workspace/scanner/walk_dir_tree.go:127 +0x45
sort.medianOfThree_func({0xc00552d778, 0xc0066698f0}, 0xc004d35590, 0x203001, 0x10)
        /usr/local/go/src/sort/zfuncversion.go:56 +0x76
sort.doPivot_func({0xc00552d778, 0xc0066698f0}, 0x0, 0xf)
        /usr/local/go/src/sort/zfuncversion.go:80 +0x115
sort.quickSort_func({0xc00552d778, 0xc0066698f0}, 0xc004d35590, 0x0, 0x0)
        /usr/local/go/src/sort/zfuncversion.go:143 +0x85
sort.Slice({0xda3c60, 0xc004d35590}, 0xf)
        /usr/local/go/src/sort/slice.go:20 +0x9f
github.com/navidrome/navidrome/scanner.fullReadDir({0x21d7980, 0xc003baa450}, {0x21d7de0, 0xc000010d78})
        /github/workspace/scanner/walk_dir_tree.go:127 +0x385
github.com/navidrome/navidrome/scanner.loadDir({0x21d7980, 0xc003baa450}, {0xc005dad860, 0x2a})
        /github/workspace/scanner/walk_dir_tree.go:77 +0x2f9
github.com/navidrome/navidrome/scanner.walkFolder({0x21d7980, 0xc003baa450}, {0xc0000a8120, 0xc}, {0xc005dad860, 0x2a}, 0xc0056974a0)
        /github/workspace/scanner/walk_dir_tree.go:39 +0x71
github.com/navidrome/navidrome/scanner.walkFolder({0x21d7980, 0xc003baa450}, {0xc0000a8120, 0xc}, {0xc0053347e0, 0x19}, 0xc0056974a0)
        /github/workspace/scanner/walk_dir_tree.go:44 +0x2c8
github.com/navidrome/navidrome/scanner.walkFolder({0x21d7980, 0xc003baa450}, {0xc0000a8120, 0xc}, {0xc0000a8120, 0xc}, 0xc00368ce28)
        /github/workspace/scanner/walk_dir_tree.go:44 +0x2c8
github.com/navidrome/navidrome/scanner.walkDirTree({0x21d7980, 0xc003baa450}, {0xc0000a8120, 0x103}, 0x0)
        /github/workspace/scanner/walk_dir_tree.go:30 +0x56
github.com/navidrome/navidrome/scanner.(*TagScanner).getRootFolderWalker.func1()
        /github/workspace/scanner/tag_scanner.go:164 +0x66
created by github.com/navidrome/navidrome/scanner.(*TagScanner).getRootFolderWalker
        /github/workspace/scanner/tag_scanner.go:163 +0x211
```

**Comment by deluan** [comment]
Hey @ahoy, are you still having this issue? Have you tried with the latest version (0.48.0)? If you are still having it, would you run a "debug" version for me? 

I see you are running on FreeBSD. Are you compiling it yourself?

**Comment by ahoy** [comment]
Let me try the new version and report back. I've been using the binary release, and using monit to restart the binary when it crashes.

**Comment by deluan** [comment]
Hey, did you get a chance to try the new version?

**Comment by ahoy** [comment]
After running for a few hours, I did get a crash. Attached is the end of the trace log.
[log.txt](https://github.com/navidrome/navidrome/files/10356330/log.txt)

**Comment by deluan** [comment]
Hey, thanks for the logs. I see the crash now happened in a completely different part of the code, but in both scenarios it happened during the scan. A workaround for you is to disable scan completely (`ScanSchedule = "0"`) and only trigger a scan when you actually modify your library.

You reported you are using FreeBSD, but we don't provide any FreeBSD binary. How are you installing it?

**Comment by ahoy** [comment]
I run the Linux binary with FreeBSD's Linux compatibility mode using the base from CentOS 7.9.2009. My guess is that is the issue, and if you have any patches to try, I'll be happy to try them out.

Thanks for the suggestion, I'll turn off the scanner and see if that stops the crash.

**Comment by ahoy** [comment]
I'll confirm that the program has been running over a week at this point, and no crashes. It certainly seems to point to the scanning function as the source of the crash.

**Comment by jan666** [comment]
I use navidrome on FreeBSD, too. No crashes. I use a self compiled binary (it's just gmake setup and gmake buildall, really simple)

**Comment by ahoy** [comment]
Thanks @jan666, I'll give that a try.

**Comment by ahoy** [comment]
After a few days of running with a self-compiled binary, I'm not seeing the crash. I'm going to close this as an artifact of running a pre-compiled binary on a system it wasn't necessarily designed for.
