### ISSUE TITLE
Segfault when SIGINT interrupts scan

### ISSUE THREAD

**Issue by vs49688** [navidrome/navidrome#2133]
### Description

A fresh Navidrome installation segfaults after receiving a SIGINT.

### Expected Behaviour

Not to segfault.

### Steps to reproduce

1. Run navidrome in an empty folder.
2. Wait for `Navidrome server is ready!`
3. Send SIGINT (or Ctrl+C)
4. Observe segfault

### Platform information

 - Navidrome version: v0.49.0
 - Browser and version: N/A
 - Operating System: NixOS 23.05.20230120.5ed4819 (Stoat)

### Additional information

Seems to occur when interrupting the scanner.

```
INFO[0000] Mounting Public Endpoints routes              path=/share
INFO[0000] Mounting LastFM Auth routes                   path=/api/lastfm
INFO[0000] Mounting ListenBrainz Auth routes             path=/api/listenbrainz
INFO[0000] Mounting Background images routes             path=/backgrounds
INFO[0000] Mounting WebUI routes                         path=/app
INFO[0000] Navidrome server is ready!                    address="0.0.0.0:4533" startupTime=158.6ms
^CINFO[0000] Received termination signal                   signal=interrupt
INFO[0001] Stopping HTTP server                         
ERRO[0002] Error stating dir                             error="stat music: no such file or directory" path=music
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x5c pc=0xc2386d]

goroutine 74 [running]:
github.com/navidrome/navidrome/scanner.isDirEmpty({0x23af030?, 0xc0006e45a0?}, {0xc000355db7?, 0xc000388dc8?})
        github.com/navidrome/navidrome/scanner/tag_scanner.go:171 +0x2d
github.com/navidrome/navidrome/scanner.(*TagScanner).Scan(0xc0004631d0, {0x23aef88?, 0xc00028b980?}, {0x5?, 0x5?, 0x0?}, 0x0?)
        github.com/navidrome/navidrome/scanner/tag_scanner.go:85 +0x15a
github.com/navidrome/navidrome/scanner.(*scanner).rescan(0xc000208c00, {0x23aef88?, 0xc00028b980}, {0xc000355db7, 0x5}, 0x0)
        github.com/navidrome/navidrome/scanner/scanner.go:92 +0x3d6
github.com/navidrome/navidrome/scanner.(*scanner).RescanAll(0xc000208c00, {0x23aef88, 0xc00028b980}, 0x1?)
        github.com/navidrome/navidrome/scanner/scanner.go:149 +0x1d3
github.com/navidrome/navidrome/cmd.schedulePeriodicScan.func1()
        github.com/navidrome/navidrome/cmd/root.go:127 +0x25b
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
```

**Comment by deluan** [comment]
I was not able to reproduce it on my side (macOS and Ubuntu), but I put a guard agains the nil pointer error. Can you confirm it works now?

**Comment by deluan** [comment]
```
ERRO[0002] Error stating dir                             error="stat music: no such file or directory" path=music
ERRO[0002] Error importing MediaFolder                   error="stat music: no such file or directory" folder=music
```

Why the music folder is suddenly unavailable when Navidrome receives a SIGINT? That's the part I can't reproduce.... If you don't interrupt it, can you actually see the music?
