### ISSUE TITLE
[Bug]: Error obtaining new orm instance - nil pointer defererence

### ISSUE THREAD

**Issue by gjedeer** [navidrome/navidrome#2412]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3 (8b93962f)

### Current Behavior

Lots of errors like this one in the logs:

```
navidrome  | time="2023-06-23T18:33:36Z" level=error msg="Error obtaining new orm instance" error="register db Ping `default`, database is locked"
navidrome  | 
navidrome  |  panic: runtime error: invalid memory address or nil pointer dereference
navidrome  |  
navidrome  |  -> github.com/navidrome/navidrome/persistence.sqlRepository.queryOne
navidrome  |  ->   /github/workspace/persistence/sql_base_repository.go:149
navidrome  | 
navidrome  |     github.com/navidrome/navidrome/persistence.(*userRepository).FindByUsername
navidrome  |       /github/workspace/persistence/user_repository.go:96
navidrome  |     github.com/navidrome/navidrome/server.contextWithUser
navidrome  |       /github/workspace/server/auth.go:216
navidrome  |     github.com/navidrome/navidrome/server.authenticateRequest
navidrome  |       /github/workspace/server/auth.go:238
navidrome  |     github.com/navidrome/navidrome/server.Authenticator.func1.1
navidrome  |       /github/workspace/server/auth.go:244
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/go-chi/chi/v5.(*ChainHandler).ServeHTTP
navidrome  |       /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/chain.go:31
navidrome  |     github.com/go-chi/chi/v5.(*Mux).routeHTTP
navidrome  |       /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/mux.go:444
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/go-chi/chi/v5.(*Mux).ServeHTTP
navidrome  |       /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/mux.go:73
navidrome  |     github.com/go-chi/chi/v5.(*Mux).Mount.func1
navidrome  |       /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/mux.go:316
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/go-chi/chi/v5.(*ChainHandler).ServeHTTP
navidrome  |       /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/chain.go:31
navidrome  |     github.com/go-chi/chi/v5.(*Mux).routeHTTP
navidrome  |       /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/mux.go:444
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/go-chi/jwtauth/v5.Verify.func1.1
navidrome  |       /go/pkg/mod/github.com/go-chi/jwtauth/v5@v5.1.0/jwtauth.go:73
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/navidrome/navidrome/server.authHeaderMapper.func1
navidrome  |       /github/workspace/server/auth.go:178
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/navidrome/navidrome/server.robotsTXT.func1.1
navidrome  |       /github/workspace/server/middlewares.go:73
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/navidrome/navidrome/server.requestLogger.func1
navidrome  |       /github/workspace/server/middlewares.go:31
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/navidrome/navidrome/server.loggerInjector.func1
navidrome  |       /github/workspace/server/middlewares.go:62
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/navidrome/navidrome/server.clientUniqueIDMiddleware.func1
navidrome  |       /github/workspace/server/middlewares.go:147
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/navidrome/navidrome/server.serverAddressMiddleware.func1
navidrome  |       /github/workspace/server/middlewares.go:157
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/go-chi/chi/v5/middleware.Heartbeat.func1.1
navidrome  |       /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/middleware/heartbeat.go:21
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/go-chi/chi/v5/middleware.(*Compressor).Handler.func1
navidrome  |       /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/middleware/compress.go:213
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/go-chi/chi/v5/middleware.Recoverer.func1
navidrome  |       /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/middleware/recoverer.go:43
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/go-chi/chi/v5/middleware.RealIP.func1
navidrome  |       /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/middleware/realip.go:36
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/go-chi/chi/v5/middleware.RequestID.func1
navidrome  |       /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/middleware/request_id.go:76
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/go-chi/cors.(*Cors).Handler.func1
navidrome  |       /go/pkg/mod/github.com/go-chi/cors@v1.2.1/cors.go:228
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/unrolled/secure.(*Secure).Handler.func1
navidrome  |       /go/pkg/mod/github.com/unrolled/secure@v1.13.0/secure.go:203
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/go-chi/chi/v5.(*Mux).ServeHTTP
navidrome  |       /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/mux.go:90
navidrome  |     net/http.serverHandler.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2947
navidrome  |     net/http.(*conn).serve
navidrome  |       /usr/local/go/src/net/http/server.go:1991
navidrome  |     created by net/http.(*Server).Serve
navidrome  |       /usr/local/go/src/net/http/server.go:3102
navidrome  |     
navidrome  | time="2023-06-23T18:33:37Z" level=error msg="Error accessing image cache" error="context deadline exceeded" id=al-76f98a87a054d2ea085d654be1dcc124_4e942242 size=0
```

### Expected Behavior

No memory errors

### Steps To Reproduce

1. Start the Docker container
2. Wait

### Environment

```markdown
- OS: Ubuntu 22.04
```

### How Navidrome is installed?

Docker

### Configuration

```toml
$ cat docker-compose.yaml 
version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 1000:1000
    environment:
      - "ND_BASEURL=/navidrome"
    volumes:
      - /docker/navidrome:/data
      - /media/music:/music:ro
    ports:
      - 4040:4533
    restart: always
```
```


### Relevant log output

```shell
navidrome  | time="2023-06-23T18:33:36Z" level=error msg="Error obtaining new orm instance" error="register db Ping `default`, database is locked"
navidrome  | 
navidrome  |  panic: runtime error: invalid memory address or nil pointer dereference
navidrome  |  
navidrome  |  -> github.com/navidrome/navidrome/persistence.sqlRepository.queryOne
navidrome  |  ->   /github/workspace/persistence/sql_base_repository.go:149
navidrome  | 
navidrome  |     github.com/navidrome/navidrome/persistence.(*userRepository).FindByUsername
navidrome  |       /github/workspace/persistence/user_repository.go:96
navidrome  |     github.com/navidrome/navidrome/server.contextWithUser
navidrome  |       /github/workspace/server/auth.go:216
navidrome  |     github.com/navidrome/navidrome/server.authenticateRequest
navidrome  |       /github/workspace/server/auth.go:238
navidrome  |     github.com/navidrome/navidrome/server.Authenticator.func1.1
navidrome  |       /github/workspace/server/auth.go:244
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/go-chi/chi/v5.(*ChainHandler).ServeHTTP
navidrome  |       /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/chain.go:31
navidrome  |     github.com/go-chi/chi/v5.(*Mux).routeHTTP
navidrome  |       /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/mux.go:444
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/go-chi/chi/v5.(*Mux).ServeHTTP
navidrome  |       /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/mux.go:73
navidrome  |     github.com/go-chi/chi/v5.(*Mux).Mount.func1
navidrome  |       /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/mux.go:316
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/go-chi/chi/v5.(*ChainHandler).ServeHTTP
navidrome  |       /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/chain.go:31
navidrome  |     github.com/go-chi/chi/v5.(*Mux).routeHTTP
navidrome  |       /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/mux.go:444
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/go-chi/jwtauth/v5.Verify.func1.1
navidrome  |       /go/pkg/mod/github.com/go-chi/jwtauth/v5@v5.1.0/jwtauth.go:73
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/navidrome/navidrome/server.authHeaderMapper.func1
navidrome  |       /github/workspace/server/auth.go:178
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/navidrome/navidrome/server.robotsTXT.func1.1
navidrome  |       /github/workspace/server/middlewares.go:73
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/navidrome/navidrome/server.requestLogger.func1
navidrome  |       /github/workspace/server/middlewares.go:31
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/navidrome/navidrome/server.loggerInjector.func1
navidrome  |       /github/workspace/server/middlewares.go:62
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/navidrome/navidrome/server.clientUniqueIDMiddleware.func1
navidrome  |       /github/workspace/server/middlewares.go:147
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/navidrome/navidrome/server.serverAddressMiddleware.func1
navidrome  |       /github/workspace/server/middlewares.go:157
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/go-chi/chi/v5/middleware.Heartbeat.func1.1
navidrome  |       /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/middleware/heartbeat.go:21
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/go-chi/chi/v5/middleware.(*Compressor).Handler.func1
navidrome  |       /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/middleware/compress.go:213
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/go-chi/chi/v5/middleware.Recoverer.func1
navidrome  |       /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/middleware/recoverer.go:43
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/go-chi/chi/v5/middleware.RealIP.func1
navidrome  |       /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/middleware/realip.go:36
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/go-chi/chi/v5/middleware.RequestID.func1
navidrome  |       /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/middleware/request_id.go:76
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/go-chi/cors.(*Cors).Handler.func1
navidrome  |       /go/pkg/mod/github.com/go-chi/cors@v1.2.1/cors.go:228
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/unrolled/secure.(*Secure).Handler.func1
navidrome  |       /go/pkg/mod/github.com/unrolled/secure@v1.13.0/secure.go:203
navidrome  |     net/http.HandlerFunc.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2109
navidrome  |     github.com/go-chi/chi/v5.(*Mux).ServeHTTP
navidrome  |       /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/mux.go:90
navidrome  |     net/http.serverHandler.ServeHTTP
navidrome  |       /usr/local/go/src/net/http/server.go:2947
navidrome  |     net/http.(*conn).serve
navidrome  |       /usr/local/go/src/net/http/server.go:1991
navidrome  |     created by net/http.(*Server).Serve
navidrome  |       /usr/local/go/src/net/http/server.go:3102
navidrome  |     
navidrome  | time="2023-06-23T18:33:37Z" level=error msg="Error accessing image cache" error="context deadline exceeded" id=al-76f98a87a054d2ea085d654be1dcc124_4e942242 size=0
```

### Anything else?

I'm trying Navidrome for the first time, everything is at default settings, the data directory was empty. The files were created OK so it's not a permission problem:

```
$ ls -n -l /docker/navidrome/
total 6186
drwxr-xr-x 4 1000 1000       4 Jun 23 18:23 cache
-rw-r--r-- 1 1000 1000 1515520 Jun 23 18:39 navidrome.db
-rw-r--r-- 1 1000 1000   32768 Jun 23 18:39 navidrome.db-shm
-rw-r--r-- 1 1000 1000 4688592 Jun 23 18:39 navidrome.db-wal
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by dweymouth** [comment]
According to this https://www.beekeeperstudio.io/blog/how-to-solve-sqlite-database-is-locked-error the "database is locked" error is likely due to another process having the DB open. Are you sure you don't have another instance of navidrome running in another container, or directly? In any case, you are right that there's a bug here since Navidrome should be able to gracefully handle this and not get a nil pointer error.

**Comment by gjedeer** [comment]
I only created the docker-compose file and ran docker-compose `pull` and then `up -d`, once.

It's also not happening any more - maybe the initial indexing was creating extra copies of navidrome?

**Comment by tedder** [comment]
I'm having this issue as well.  There's definitely nothing else accessing the DB.

```
navidrome_1     | time="2023-09-05T20:11:04Z" level=error msg="Error obtaining new orm instance" error="register db Ping `default`, database is locked"
navidrome_1     | 
navidrome_1     |  panic: runtime error: invalid memory address or nil pointer dereference
...
navidrome_1     | time="2023-09-05T20:11:05Z" level=error msg="Error obtaining new orm instance" error="register db Ping `default`, database is locked"
navidrome_1     | panic: runtime error: invalid memory address or nil pointer dereference
navidrome_1     | [signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0xa036be]
navidrome_1     | 
navidrome_1     | goroutine 163007 [running]:
navidrome_1     | github.com/navidrome/navidrome/persistence.sqlRepository.queryAll({{0x25817b8, 0xc000156f90}, {0x10dfa9e, 0xa}, {0x0, 0x0}, 0xc002122b10}, {0x257bb20?, 0xc002382140?}, {0xfdb6a0, ...})
navidrome_1     | 	/github/workspace/persistence/sql_base_repository.go:164 +0xde
navidrome_1     | github.com/navidrome/navidrome/persistence.(*mediaFileRepository).FindAllByPath(0xc002380000, {0xc001e2a720?, 0xc000156f90?})

```

**Comment by uumas** [comment]
Seeing the exact same error on a plain linux server (debian bullseye), running from the 0.49.3 x86_64 binary. Also a new server, first had this problem after it had been running for ~ 30 minutes, but really soon after I started actually using it (I let it process the media folders before I started testing it out). After that seen three crashes in the past hour.

**Comment by deluan** [comment]
Hey folks, is this still happening with the latest 0.51.0? The DB code had a significant rewrite, so this bug may not happen anymore. 

Please let me know.
