### ISSUE TITLE
[Bug]: Jukebox mode under Windows (wasapi exclusive output)

### ISSUE THREAD

**Issue by korzhyc** [navidrome/navidrome#2780]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [ ] I'm using the latest version (your issue may have been fixed already)

### Version

0.50.1-SNAPSHOT (badc0cb5)

### Current Behavior

mpv is configured to use exclusive output mode.
During playback when the current track ends, Navidrome crashes with a critical error.
However, manual switching between tracks is okay.

### Expected Behavior

No panic.

### Environment

```markdown
- Server: Windows Server 2022, mpv-0.37.0-x86_64-v3
- Client: DSub 5.5.3, Ultrasonic 4.8.0
```

### How Navidrome is installed?

Built from sources

### Configuration

```toml
mpv.conf:
input-default-bindings=no
load-stats-overlay=no
load-auto-profiles=no
load-osd-console=no
load-scripts=no
ytdl=no
osc=no
vid=no
audio-display=no
autoload-files=no
audio-pitch-correction=no
volume-max=100
volume=100
audio-exclusive=yes

navidrome.toml:
LogLevel = 'debug'
DataFolder = '.\data'
MusicFolder = 'F:\Music'
Jukebox.Enabled = true
Jukebox.Devices = [
  ['realtek_spdif', 'wasapi/{eebf0aab-21a9-4d68-8759-22f533c960e7}']
]
MPVPath = 'C:\Srv\Navidrome\jukebox\mpv.com'
```

### Relevant log output

```shell
mpv.log when manually switching to the next track:
...
[   0.090][d][ao/wasapi] Thread Reset
[  23.291][d][ao/wasapi] Thread Reset
[  23.291][v][cplayer] Set property: pause=true -> 1
[  23.291][d][cplayer] Run command: quit, flags=64, args=[code="0"]
[  23.291][v][cplayer] EOF code: 5  
[  23.291][d][ad] Uninit decoder.
[  23.291][v][ipc_2] Client connected
[  23.291][v][ipc_2] Client disconnected
[  23.291][d][ipc_2] Exiting...
[  23.291][d][cplayer] Terminating demuxers...
[  23.292][d][cplayer] Done terminating demuxers.
[  23.292][v][cplayer] finished playback, success (reason 3)
[  23.292][i][cplayer] Exiting... (Quit)
[  23.292][d][ipc_1] Exiting...
[  23.293][v][ipc_3] Client connected
[  23.293][v][ipc_3] Client disconnected
[  23.293][d][ipc_3] Exiting...


mpv.log when reaching the end of the track (exclusive off):
...
[   0.090][d][ao/wasapi] Thread Reset
[ 488.259][v][lavf] EOF reached.
[ 489.238][v][af] filter input EOF
[ 489.238][v][af] filter output EOF
[ 489.238][v][cplayer] audio filter EOF
[ 489.238][v][cplayer] audio draining
[ 489.238][v][cplayer] audio EOF reached
[ 489.238][v][cplayer] EOF code: 1  
[ 489.238][d][ad] Uninit decoder.
[ 489.238][d][cplayer] Terminating demuxers...
[ 489.239][d][cplayer] Done terminating demuxers.
[ 489.239][v][cplayer] finished playback, success (reason 0)
[ 489.239][i][cplayer] Exiting... (End of file)
[ 489.239][d][ipc_1] Exiting...
[ 489.239][v][cplayer] draining left over audio
[ 489.468][d][ao/wasapi] Uninit wasapi
[ 489.468][d][ao/wasapi] Thread Reset
[ 489.468][d][ao/wasapi] Thread Reset
[ 489.468][d][ao/wasapi] Thread shutdown
[ 489.469][d][ao/wasapi] Thread uninit done
[ 489.469][d][ao/wasapi] Thread return
[ 489.469][d][ao/wasapi] Uninit wasapi done


mpv.log when reaching the end of the track:
...
[   0.021][e][ao/wasapi] Error initializing device: AUDCLNT_E_DEVICE_IN_USE (0x8889000a)
[   0.022][w][ao/wasapi] Retrying in 1000 ns
...
[   0.043][i][cplayer] Exiting... (Errors when loading file)


navidrome.log when reaching the end of the track:
...
time="2024-01-08T16:06:23+03:00" level=info msg="Hitting end-of-stream, signalling on channel"
time="2024-01-08T16:06:23+03:00" level=debug msg="Track switching detected"
time="2024-01-08T16:06:23+03:00" level=debug msg="closing resources"
time="2024-01-08T16:06:23+03:00" level=debug msg="Switching to next song" queue="#Items: 14, idx: 3, files: [REDACTED] "
time="2024-01-08T16:06:23+03:00" level=debug msg="Loading track" mediaType=audio/ogg trackPath="F:\\Music\\-COLLECT\\Ally Nicholas - I Know You Too Well [ZmnT8djcs9Y].opus"
time="2024-01-08T16:06:23+03:00" level=debug msg="Executing mpv command" cmd="[C:\\Srv\\Navidrome\\jukebox\\mpv.com --audio-device=wasapi/{eebf0aab-21a9-4d68-8759-22f533c960e7} --no-audio-display --pause F:\\Music\\-COLLECT\\Ally Nicholas - I Know You Too Well [ZmnT8djcs9Y].opus --input-ipc-server=\\\\.\\pipe\\mpvsocket\\mpv-ctrl-f8edad01faec448d40b0bc7d9f42130a.socket]"
time="2024-01-08T16:06:24+03:00" level=debug msg="API: New request /rest/jukeboxControl.view" client=Ultrasonic requestId=WIN-6H9506BP7VG/EyafwyVzCn-000069 username=admin version=1.16.0
time="2024-01-08T16:06:24+03:00" level=debug msg="Processing GetDevice" user=admin
time="2024-01-08T16:06:24+03:00" level=info msg="JukeboxControl request received" action=status requestId=WIN-6H9506BP7VG/EyafwyVzCn-000069 username=admin
time="2024-01-08T16:06:24+03:00" level=debug msg="processing Status action on: Name: realtek_spdif, Gain: 1.0000, Loaded track: %!s(<nil>), queue: #Items: 14, idx: 3, files: [REDACTED] " requestId=WIN-6H9506BP7VG/EyafwyVzCn-000069 username=admin
time="2024-01-08T16:06:24+03:00" level=debug msg="API: Successful response" endpoint=/rest/jukeboxControl.view requestId=WIN-6H9506BP7VG/EyafwyVzCn-000069 status=OK username=admin
time="2024-01-08T16:06:24+03:00" level=debug msg="HTTP: GET http://10.0.2.11:4533/rest/jukeboxControl.view?action=status&u=admin&c=Ultrasonic&f=json&v=1.16.0&t=[REDACTED]&s=[REDACTED]" elapsedTime="514.7µs" httpStatus=200 remoteAddr="10.0.2.3:55191" requestId=WIN-6H9506BP7VG/EyafwyVzCn-000069 responseSize=213 userAgent=okhttp/4.11.0
time="2024-01-08T16:06:26+03:00" level=error msg="Error or timeout waiting for control socket" error="timeout reached: 3s" socketname="\\\\.\\pipe\\mpvsocket\\mpv-ctrl-f8edad01faec448d40b0bc7d9f42130a.socket"
time="2024-01-08T16:06:26+03:00" level=error msg="Error switching track" error="timeout reached: 3s"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x50 pc=0x146f14f]
goroutine 100 [running]:
github.com/navidrome/navidrome/core/playback.(*playbackDevice).trackSwitcherGoroutine(0xc000499f80)
	/github/workspace/core/playback/device.go:272 +0x28f
github.com/navidrome/navidrome/core/playback.(*playbackDevice).Start.func1()
	/github/workspace/core/playback/device.go:110 +0x17
created by github.com/navidrome/navidrome/core/playback.(*playbackDevice).Start in goroutine 87
	/github/workspace/core/playback/device.go:109 +0x189
```

### Anything else?

https://github.com/mpv-player/mpv/issues/9535

Pause that causes device lock:
https://github.com/mpv-player/mpv/blob/818ce7c51a6b9179307950e919983e0909942098/audio/out/buffer.c#L453

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by ms140569** [comment]
Thanks for reporting this and sorry, that this took so long. I've added a guard against this crashing navidrome:

https://github.com/navidrome/navidrome/pull/2996
