### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by joakimlemb** [navidrome/navidrome#3118]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.52.5 (c5560888)

### Current Behavior

Navidrome is crashing with the following smart playlist:

```
{
	"all": [
		{
			"contains": {
				"genre": "Hardcore",
				"filetype": "mp3"
			}
		}
	],
	"order": "asc",
	"sort": "artist"
}
```

I'm trying to create a playlist with only .mp3 files, works fine with just the genre defined like this:
```
{
	"all": [
		{
			"contains": {
				"genre": "Hardcore"
			}
		}
	],
	"order": "asc",
	"sort": "artist"
}
```

### Expected Behavior

A smart playlist with only .mp3 files is added.

### Steps To Reproduce

Create smart playlist file with the following contents, then restart container or do a full rescan:
```
{
	"all": [
		{
			"contains": {
				"genre": "Hardcore",
				"filetype": "mp3"
			}
		}
	],
	"order": "asc",
	"sort": "artist"
}
```

### Environment

```markdown
OS: Debian 12.5
```

### How Navidrome is installed?

Docker

### Configuration

```toml
navidrome:
    hostname: navidrome
    image: deluan/navidrome:latest
    mem_limit: 1g
    user: 1000:1000
    ports:
      - 4533:4533
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
      ND_ENABLESHARING: "true"
      ND_PASSWORDENCRYPTIONKEY: "REDACTED"
      ND_AUTOIMPORTPLAYLISTS: "true"
      ND_DEFAULTTHEME: "Nord"
      ND_LASTFM_ENABLED: "true"
      ND_LASTFM_APIKEY: "REDACTED"
      ND_LASTFM_SECRET: "REDACTED"
      ND_LISTENBRAINZ_ENABLED: "false"
      ND_SCANNER_EXTRACTOR: "ffmpeg"
    volumes:
      - "/REDACTED/navidrome:/data"
      - "/REDACTED:/music:ro"
    logging:
      options:
       max-size: "5m"
    labels:
      - homepage.group=Docker
      - homepage.name=Navidrome
      - homepage.icon=navidrome.png
      - homepage.href=REDACTED
      - homepage.description=Music server and streamer.
```

### Relevant log output

```shell
navidrome-1  | time="2024-06-25T17:54:31Z" level=info msg="Adding synced playlist" owner=REDACTED path=/music/Playlists/test_filetype.nsp playlist=test_filetype
navidrome-1  | panic: assignment to entry in nil map
navidrome-1  |
navidrome-1  | goroutine 86 [running]:
navidrome-1  | github.com/navidrome/navidrome/persistence.sqlRepository.put({{0x2796170, 0xc0004911a0}, {0x1113fdd, 0x8}, {0x27a2790, 0xc0000ea230}, 0x0}, {0x0, 0x0}, {0x10a0cc0, ...}, ...)
navidrome-1  |  /__w/navidrome/navidrome/persistence/sql_base_repository.go:285 +0x1b0
navidrome-1  | github.com/navidrome/navidrome/persistence.(*playlistRepository).Put(0xc00064b8c0, 0xc000555420)
navidrome-1  |  /__w/navidrome/navidrome/persistence/playlist_repository.go:121 +0x1f3
navidrome-1  | github.com/navidrome/navidrome/core.(*playlists).updatePlaylist(0xc0002480b0, {0x2796170, 0xc0004911a0}, 0xc000555420)
navidrome-1  |  /__w/navidrome/navidrome/core/playlists.go:197 +0x573
navidrome-1  | github.com/navidrome/navidrome/core.(*playlists).ImportFile(0xc0002480b0, {0x2796170, 0xc0004911a0}, {0xc0003a9280, 0x10}, {0xc000576558, 0x11})
navidrome-1  |  /__w/navidrome/navidrome/core/playlists.go:45 +0x390
navidrome-1  | github.com/navidrome/navidrome/scanner.(*playlistImporter).processPlaylists(0xc0002ac180, {0x2796170, 0xc0004911a0}, {0xc0003a9280, 0x10})
navidrome-1  |  /__w/navidrome/navidrome/scanner/playlist_importer.go:45 +0x28a
navidrome-1  | github.com/navidrome/navidrome/scanner.(*TagScanner).Scan(0xc0000c0230, {0x27961e0?, 0xc000568160?}, {0x5?, 0x6?, 0x2e60480?}, 0xc0001fc600)
navidrome-1  |  /__w/navidrome/navidrome/scanner/tag_scanner.go:157 +0x1225
navidrome-1  | github.com/navidrome/navidrome/scanner.(*scanner).rescan(0xc0004963c0, {0x27961e0, 0xc000568160}, {0xc00003e09f, 0x6}, 0x0)
navidrome-1  |  /__w/navidrome/navidrome/scanner/scanner.go:95 +0x3cb
navidrome-1  | github.com/navidrome/navidrome/scanner.(*scanner).RescanAll(0xc0004963c0, {0x27961a8?, 0xc0000c00f0?}, 0x0)
navidrome-1  |  /__w/navidrome/navidrome/scanner/scanner.go:193 +0x225
navidrome-1  | github.com/navidrome/navidrome/cmd.runNavidrome.schedulePeriodicScan.func4()
navidrome-1  |  /__w/navidrome/navidrome/cmd/root.go:150 +0x22a
navidrome-1  | golang.org/x/sync/errgroup.(*Group).Go.func1()
navidrome-1  |  /go/pkg/mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78 +0x56
navidrome-1  | created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
navidrome-1  |  /go/pkg/mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:75 +0x96
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
Ah, just realized the error: The syntax is wrong! Each operator can only have one pair of field/value. The correct syntax would be:

```json
{
  "all": [
    {
      "contains": {
        "genre": "Hardcore"
      }
    },
    {
      "is": {
        "filetype": "mp3"
      }
    }
  ],
  "order": "asc",
  "sort": "artist"
}
```

Anyway, thanks for reprting this. I'll change the code to detect the invalid syntax
