### ISSUE TITLE
[Bug]: Fails to build on FreeBSD

### ISSUE THREAD

**Issue by jan666** [navidrome/navidrome#3390]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

latesr from main

### Current Behavior

When I try to build navidrome from source I get the followin error

```
# gmake build

> build
> vite build

/root/navidrome/ui/node_modules/rollup/dist/native.js:84
        throw new Error(
              ^

Error: Your current platform "freebsd" and architecture "x64" combination is not yet supported by the native Rollup build. Please use the WASM build "@rollup/wasm-node" instead.

The following platform-architecture combinations are supported:
android-arm
android-arm64
darwin-arm64
darwin-x64
linux-arm
linux-arm (musl)
linux-arm64
linux-arm64 (musl)
linux-ppc64
linux-riscv64
linux-s390x
linux-x64
linux-x64 (musl)
win32-arm64
win32-ia32
win32-x64

If this is important to you, please consider supporting Rollup to make a native build for your platform and architecture available.
    at throwUnsupportedError (/root/navidrome/ui/node_modules/rollup/dist/native.js:84:8)
    at getPackageBase (/root/navidrome/ui/node_modules/rollup/dist/native.js:75:3)
    at Object.<anonymous> (/root/navidrome/ui/node_modules/rollup/dist/native.js:37:21)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at cjsLoader (node:internal/modules/esm/translators:346:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:286:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)

Node.js v20.18.0
gmake: *** [Makefile:98: ui/build/index.html] Error 1
```

I tried to add an override in `ui/package.json` (https://github.com/vitejs/vite/issues/15122) and update the `package-lock.json` (`npm i --package-lock-only`)

but then I end up with this error:

```
 # gmake build

> build
> vite build

failed to load config from /root/navidrome/ui/vite.config.js
error during build:
Error: Failed to load native binding
    at Object.<anonymous> (/root/navidrome/ui/node_modules/@swc/core/binding.js:333:11)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/root/navidrome/ui/node_modules/@swc/core/index.js:49:17)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
gmake: *** [Makefile:98: ui/build/index.html] Error 1
```

### Expected Behavior

Navidrome should build on FreeBSD

### Environment

```markdown
- OS: FreeBSD
- Browser:
- Client:
```

### How Navidrome is installed?

Built from sources

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by jan666** [comment]
It looks like `@vitejs/plugin-react-swc` does not work on FreeBSD. 

I changed the package.json

```
+  "overrides": {
+    "vite": {
+      "rollup": "npm:@rollup/wasm-node"
+    }
+  },
```

```
-    "@vitejs/plugin-react-swc": "^3.7.1",
+    "@vitejs/plugin-react": "^4.3.2",
```

and `ui/vite.config.js`

```
-import react from '@vitejs/plugin-react-swc'
+import react from '@vitejs/plugin-react'
```

deleted `package-lock.json` and `node_modules`, ran `npm i --package-lock-only` to re-generate the `package-lock.json`. After that I was able to build navidrome again (using `gmake setup && gmake build`).

**Comment by deluan** [comment]
Cool, thanks for reporting. I'm ok replacing `@vitejs/plugin-react-swc` with `@vitejs/plugin-react`, as Navidrome UI is not a huge JS project and the performance difference is negligible.

Can you provide a PR, please?

**Comment by jan666** [comment]
How to deal with the `overrides`?

**Comment by deluan** [comment]
If it is required, add it at the end of the `package.json` and I'll test your PR in macOS and Linux

**Comment by jan666** [comment]
See PR #3403

just for documentation: to push I had to change "make" to "gmake" in `git/pre-push` (not committed)
